42 UI update
Group14-Newbank/newbank pull request #29
Opened 2021-04-05 11:47 UTC by artem-kim

2021-04-05 17:13 UTC, michowski reviewed
Hi Artem. It would be awesome to add a few tests for this perhaps, as I already have some ideas how we could refactor it to utilize the command names from command classes.

Best!
Arek

2021-04-05 20:51 UTC, michowski commented
Also, some conflicts to resolve.

2021-04-05 21:39 UTC, ZacTredger requested changes
Agree with Arek: It'll need rebasing onto main, which might be quite tricky, so some tests would be a good idea to catch regressions.
Might also be a good idea to do an interactive rebase if you're up to it and squash some of the commits together.

2021-04-05 21:39 UTC, ZacTredger commented on src/main/java/newbank/server/NewBankClientHandler.java
> +    out.println("OPTION 5. QUIT - quit the menu"
Missing a `);` at the end of this line

2021-04-05 21:39 UTC, ZacTredger commented on src/main/java/newbank/server/NewBankClientHandler.java
> +    out.println("OPTION 4. PAY <Person/Company> <Ammount> - pay another person (COMING SOON)");
Typo: "Ammount"

2021-04-06 04:39 UTC, jkonan100 commented
Morning @artem-kim ,
Could you please catch up with "main", resolve the conflicts and push again? I can't try it as your code is out of synch with main.
Thanks

Kindest Regards,
Jules

2021-04-13 18:11 UTC, michowski commented
Heya @artem-kim! Are you continuing on this branch or shall we close the PR?

2021-04-13 18:13 UTC, artem-kim commented
Good to close!

2021-04-13 23:04 UTC, closed without merging